### ISSUE TITLE
Support for Deep Learning Libraries

### ISSUE THREAD

**Issue by yuvi17** [openebs/easy-jupyter#8]
Adding support for using deep learning libraries `tensorflow` and `keras` to the docker build. This will allow this image to be potentially used for deep learning tasks as well.

**Comment by yuvi17** [comment]
I would like to take this up.

**Comment by kmova** [comment]
Merged via https://github.com/openebs/easy-jupyter/pull/11.

**Comment by kmova** [comment]
As it is miss on my part, would love to account this as part of the 2020 hacktoberfest. You can sign up for Hacktoberfest swag from MayaData by entering details here: https://github.com/mayadata-io/swag/issues/new/choose

**Comment by yuvi17** [comment]
@kmova Thanks for this. Slipped from my mind as well. Happy to help.
